// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxLab.Data;

#nullable disable

namespace TaxLab.Data.Migrations;

[DbContext(typeof(TaxLabDbContext))]
partial class TaxLabDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.0");

        modelBuilder.Entity("TaxLab.Data.Entities.TaxRateEntry", b =>
        {
            b.Property<Guid>("TaxRateId")
                .ValueGeneratedOnAdd()
                .HasColumnType("TEXT");

            b.Property<decimal>("BandStart")
                .HasColumnType("TEXT");

            b.Property<decimal?>("BandFinish")
                .HasColumnType("TEXT");

            b.Property<decimal>("TaxRate")
                .HasColumnType("TEXT");

            b.Property<DateTime>("CreatedDateUTC")
                .HasColumnType("TEXT");

            b.HasKey("TaxRateId");

            b.ToTable("TaxRates");
        });
#pragma warning restore 612, 618
    }
}
